// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full sticky top-0 z-50\"><nav><div id=\"logo-container\" class=\"flex ml-0\"><img id=\"nav-logo\" alt=\"Belle&#39;s Crafts Logo\" src=\"/static/assets/belle-logo.svg\" class=\"h-20 w-auto\"></div><div id=\"nav-container\" class=\"flex justify-center items-center container max-w-1200\"><ul class=\"list-none m-0 p-0 flex-grow gap-10\"><li id=\"nav_link\"><a id=\"homelink\" href=\"/\">Home</a></li><li class=\"nav_link\"><a id=\"shoplink\" href=\"/shop\">Shop</a></li><li class=\"nav_link\"><a id=\"aboutlink\" href=\"/about\">About</a></li><li class=\"nav_link\"><a href=\"mailto:bellescrafts06@gmail.com\">Contact</a></li></ul></div></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
